main: simplecountdown.SimpleDateCountdown
version: 1.0.1
name: SimpleDateCountdown
api-version: 1.15
author: [Ardila, XavierKrostya]
softdepend:
    - LuckPerms
    - PermissionsEx
    - bPermissions
    - zPermissions
    - Multiverse-Core
    - EssentialsX
    - ProtocolLib
commands:
    simpledatecountdown:
        description: Principal SDC Command
        usage: /simpledatecountdown  info | set | delete | enable | disable | reload | remaining
        aliases:
          - countdown
          - sdc
            